### ISSUE TITLE
Start / Setup environment issues?

### ISSUE THREAD

**Issue by pramsey** [chriswhong/postgis-preview#88]
Maybe there's a version requirement that isn't documented or something? Cannot even start:
```
yarn install v1.7.0
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.43s.
Sparrow:~/Code/labs-postgis-preview pramsey(develop)$ yarn start
yarn run v1.7.0
$ node server.js
/Users/pramsey/Code/labs-postgis-preview/routes/sql.js:38
    );
    ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pramsey/Code/labs-postgis-preview/server.js:39:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Sparrow:~/Code/labs-postgis-preview pramsey(develop)$ git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
```

**Comment by eczajk1** [comment]
I believe this is related to the version of Node you are running. I encountered the same issue with v6, but switching to v10 fixed it.

The intended version could be added to the readme and package.json (see [engines](https://docs.npmjs.com/files/package.json#engines)).

**Comment by pramsey** [comment]
Yes, was a lower version and later version ran, thanks.
